### PR TITLE
luasandbox binary

### PR DESCRIPTION
**Pull request by sathieu**
This add a luasandbox binary with behavior similar to lua5.1.

### CODE REVIEW

**Comment by sathieu** [comment]
Context: We need to run tests after a package is built.

This can now be done with something like (from lpeg source):
```
LUA_INIT=' package.path="sandbox-lpeg/?.lua;sandbox-lpeg/?/init.lua;"..package.path; package.cpath="sandbox-lpeg/?.so;"..package.cpath; ' luasandbox test.lua
```
This is how lua packages are tested in Debian after building [1]. Also, package.preload in used [2].

Additionally, LUA_CPATH and LUA_PATH environment variables are handled.

Refs:
- [1] LUA_INIT: https://anonscm.debian.org/cgit/pkg-lua/dh-lua.git/tree/make/dh-lua.Makefile.single#n127
- [2]: package.preload: https://anonscm.debian.org/cgit/pkg-lua/dh-lua.git/tree/test/5.1/app.c.conf.in#n8

**Comment by trink** [comment]
Thanks for the submission but testing sandbox modules in an altered version of the sandbox is not an acceptable approach.  Instead a proper host environment should be setup around the real sandbox (similar to the lpeg grammar tester (exposing the generic sandbox), the Hindsight admin plugin tester (exposing a Heka sandbox) and the sandbox module tests.  See: https://github.com/mozilla-services/hindsight/issues/19 (we would also need something similar for the generic sandbox).  Ideally when this is generalized we could use this for the sandbox module tests instead of the custom test executables.

**Comment by sathieu** [comment]
The thing is we want to use the same tests as lua5.1, this means using upstream tests (i.e not sandbox modules tests, but lua tests like https://github.com/LuaDist/lpeg/blob/master/test.lua).

Also, having an interactive CLI will help development of lua sandbox extensions.

I'm afraid I'll need to keep this patches in Debian anyway.

**Comment by bbinet** [comment]
I also think it could be useful to have an interactive luasandbox CLI.

**Comment by trink** [comment]
From a Heka sandbox perspective an interactive CLI is impractical since it requires two functions to be defined before execution.   Have you used the Plugin tester UI.  It allows you to test your code, capture and browse test input, view debug output, and capture and browse plugin output.  The CLI wouldn't even come close to that level of usefulness for development. I have explored a number of approaches over the years the best one was a CLI plugin tester/profiler which worked well but in the end had very little user adoption.

**Pull request closed without merging**
