### PR TITLE
Handle Apache mod_ssl Custom Log Formats

### PR DESCRIPTION
**Pull request by sathieu**
As defined in http://httpd.apache.org/docs/current/mod/mod_ssl.html#logformats

### CODE REVIEW

**Comment by trink** [comment]
Can you add a test case in https://github.com/mozilla-services/lua_sandbox/blob/master/src/test/lua/lpeg_clf.lua#L266, thanks.

**Comment by sathieu** [comment]
I've added two tests, but unfortunately  can't test as I'm not able to build luad_sandbox from source (```fatal error: luasandbox/lua.h: No such file or directory```)

**Comment by trink** [comment]
hmm, please blow away your build directory and build from scratch.  If it fails send me the cmake output, thanks.

**Comment by sathieu** [comment]
Here it is:
```
mathieu@ultrathieu:~/src/github.com/mozilla-services/lua_sandbox$ rm -r release/
mathieu@ultrathieu:~/src/github.com/mozilla-services/lua_sandbox$ mkdir release
mathieu@ultrathieu:~/src/github.com/mozilla-services/lua_sandbox$ cd release
mathieu@ultrathieu:~/src/github.com/mozilla-services/lua_sandbox/release$ LANG=C cmake -DCMAKE_BUILD_TYPE=release ..
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- The Kafka module will not be built
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Found Git: /usr/bin/git (found version "2.8.0.rc3") 
Doxygen was not found, the documentation pages will not be generated
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mathieu/src/github.com/mozilla-services/lua_sandbox/release
mathieu@ultrathieu:~/src/github.com/mozilla-services/lua_sandbox/release$ LANG=C make
Scanning dependencies of target copy_includes
[  0%] Built target copy_includes
Scanning dependencies of target luasandboxutil
[  1%] Building C object src/util/CMakeFiles/luasandboxutil.dir/heka_message.c.o
In file included from /home/mathieu/src/github.com/mozilla-services/lua_sandbox/release/ep_base/include/luasandbox/util/heka_message.h:15:0,
                 from /home/mathieu/src/github.com/mozilla-services/lua_sandbox/src/util/heka_message.c:9:
/home/mathieu/src/github.com/mozilla-services/lua_sandbox/release/ep_base/include/luasandbox/util/../../luasandbox.h:68:28: fatal error: luasandbox/lua.h: No such file or directory
compilation terminated.
src/util/CMakeFiles/luasandboxutil.dir/build.make:62: recipe for target 'src/util/CMakeFiles/luasandboxutil.dir/heka_message.c.o' failed
make[2]: *** [src/util/CMakeFiles/luasandboxutil.dir/heka_message.c.o] Error 1
CMakeFiles/Makefile2:1522: recipe for target 'src/util/CMakeFiles/luasandboxutil.dir/all' failed
make[1]: *** [src/util/CMakeFiles/luasandboxutil.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by trink** [comment]
Just out of curiosity what version of cmake are you using?  Since it was running the build in a different order it uncovered a dependency that was created by an erroneous include.  Please give the latest master a try and let me know if you are seeing any other issues.  Thanks

**Comment by sathieu** [comment]
```cmake version 3.5.1```.

Rebased, but there's another one:
```
[  7%] Building C object src/CMakeFiles/luasandbox.dir/luasandbox.c.o
In file included from /home/mathieu/src/github.com/mozilla-services/lua_sandbox/src/luasandbox.c:9:0:
/home/mathieu/src/github.com/mozilla-services/lua_sandbox/release/ep_base/include/luasandbox.h:68:28: fatal error: luasandbox/lua.h: Aucun fichier ou dossier de ce type
compilation terminated.
```

**Comment by trink** [comment]
Ok, reproduce and corrected the problem with cmake 3.5.1 you should be good to go, thanks.

**Comment by sathieu** [comment]
Tests now pass. Pushed.

**Pull request merged**
