### PR TITLE
Rename the group name with time to timestamp

### PR DESCRIPTION
**Pull request by vlastv**
Result discussion https://github.com/mozilla-services/heka/pull/1752

### CODE REVIEW

**Comment by trink** [comment]
The unit tests must be updated too.

**Comment by vlastv** [comment]
This repository has no unit tests. 

I can not write from scratch test. I see LUA first time :)

**Comment by timurb** [comment]
https://github.com/mozilla-services/heka/blob/master/sandbox/plugins/sandbox_decoders_test.go ?

**Comment by trink** [comment]
It has reasonably extensive set of unit tests here: https://github.com/mozilla-services/lua_sandbox/blob/dev/src/test/lua/lpeg_clf.lua and this change breaks them. They can be run with `ctest`

**Pull request closed without merging**
