### PR TITLE
Big endian support

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by trink** [comment]
This breaks the Windows build

**Comment by sathieu** [comment]
What is the error?

(side note: how can we test this under travis, ...)

**Comment by sathieu** [comment]
Something homemade like https://github.com/majek/csiphash/pull/2/files is needed

**Comment by sathieu** [comment]
Can you enable travis now that it's merged?

**Comment by trink** [comment]
Travis has been enabled

**Comment by trink** [comment]
As for the windows support I would conditionally compile out this behavior as the there are no big endian Windows platforms being targeted.

**Comment by trink** [comment]
Closing, if this is still needed the comments should be addressed and a new PR opened against the dev branch.

**Pull request closed without merging**
