### PR TITLE
Fix big heka headers on 32-bit architectures

### PR DESCRIPTION
**Pull request by sathieu**
See https://github.com/mozilla-services/lua_sandbox/issues/168

### CODE REVIEW

**Comment by trink** [comment]
This is an exposed API it should be fixed with a cast in the function as opposed to changing the API.

**Comment by sathieu** [comment]
But a cast will not preserve API on 32 bit (as sizeof(size_t) is 4)? Should we introduce a newlsb_write_heka_header64?

**Comment by trink** [comment]
Sorry, I read this quickly and thought it was related to a compilation issue we were discussing.  As for supporting messages > 4GiB Hindsight actually limits the maximum message size to 2GiB so this would be a feature for the 32 bit  generic sandbox or an alternate wrapper of the Heka sandbox.  What is your use case?

**Comment by trink** [comment]
Sorry, I read this too quickly and related it to a different compilation issue we discussed (but the comment was correct we don't want to break the API).  As for supporting messages > 4GiB Hindsight actually limits the maximum message size to 2GiB so this would be a feature for the 32 bit  generic sandbox or an alternate wrapper of the Heka sandbox.  What is your use case?

**Comment by sathieu** [comment]
The problem is : lua_sandbox FTBFS (fails to build from source), on 32-bit or big-endian arch.

I tried to solve the 32-bit case with this case.

This is a stopper to have lua_sandbox in Debian. See https://qa.debian.org/excuses.php?package=lua-sandbox. See also build logs : https://buildd.debian.org/status/package.php?p=lua-sandbox

If we don't care about lsb_write_heka_header with size >= 32-bit, which not limit the loop to 4? See https://github.com/mozilla-services/lua_sandbox/blob/50f3eea157242aefdec60be3930faa051a2c9bf4/src/util/test/test_heka_message.c#L343

**Comment by trink** [comment]
Mozilla is having its work week this week so things may be a little less responsive/timely please bear with me; I will test and resolve the 32 bit issues at my first opportunity, thanks.

**Comment by trink** [comment]
Closed in https://github.com/mozilla-services/lua_sandbox/tree/fix_unit_tests_x86+win

**Comment by sathieu** [comment]
Thanks.

NB : this is : 6d1259196fb27c710c44b34f02c4c8ca03947f02

**Pull request closed without merging**
