### PR TITLE
Big endian support

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
This is a proposal for the big-endian part of #168.

**Comment by sathieu** [comment]
Now lsb builds correctly on all official Debian architectures, and on most unofficial ones. The two remaining are alpha and hurd-i386, but for another reason :
```
11/14 Test #11: test_heka_sandbox ..................***Failed    0.02 sec
line: 464 (0 < stats.pm_avg) received 0
Tests run: 8
```
Which looks like the test is too fast!

Ref: https://buildd.debian.org/status/package.php?p=lua-sandbox

**Comment by trink** [comment]
Please make the PR against the dev branch, thanks.

**Comment by sathieu** [comment]
Replaced by #181.

**Pull request closed without merging**
