### PR TITLE
Build and test using travis

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
The code has been organized to allow usage by lua_sandbox_extensions and hindsight.

It passes, see: https://travis-ci.org/sathieu/lua_sandbox/builds/186438906

Merry Christmas.

**Comment by sathieu** [comment]
It's not yet ready. I'll try to work on it soon.

**Comment by trink** [comment]
This is a nice xmas present :).  Please make the PR against the dev branch (even though it doesn't require a version update) as master is the current stable release.

**Comment by sathieu** [comment]
Replaced by #180.

**Pull request closed without merging**
